export const LlmsList = [
  {
    modelName: "Anthropic Claude 3.5 Sonnet",
    modelId: "anthropic.claude-3-5-sonnet-20240620-v1:0",
    shortName: "Claude Sonnet",
    modelIcon: "/assets/icons/model-icons/claude-sonnet.svg",
    provider: "aws",
  },
  {
    modelName: "Anthropic Claude 3.5 Haiku",
    modelId: "anthropic.claude-3-haiku-20240307-v1:0",
    shortName: "Claude Haiku",
    modelIcon: "/assets/icons/model-icons/claude-sonnet.svg",
    provider: "aws",
  },
  {
    modelName: "Anthropic Claude 3.7",
    modelId: "us.anthropic.claude-3-7-sonnet-20250219-v1:0",
    shortName: "Anthropic Claude 3.7",
    modelIcon: "/assets/icons/model-icons/claude-sonnet.svg",
    provider: "aws",
  },
  {
    modelName: "GPT-4o",
    modelId: "gpt-4o",
    shortName: "GPT-4o",
    modelIcon: "/assets/icons/model-icons/chatgpt.svg",
    provider: "openai",
  },
  {
    modelName: "GPT-4o-mini",
    modelId: "gpt-4o-mini",
    shortName: "GPT-40-mini",
    modelIcon: "/assets/icons/model-icons/chatgpt.svg",
    provider: "openai",
  },
  {
    modelName: "gpt-4.1",
    modelId: "gpt-4.1",
    shortName: "gpt-4.1",
    modelIcon: "/assets/icons/model-icons/chatgpt.svg",
    provider: "openai",
  },
  {
    modelName: "gpt-4.1-nano",
    modelId: "gpt-4.1-nano",
    shortName: "gpt-4.1-nano",
    modelIcon: "/assets/icons/model-icons/chatgpt.svg",
    provider: "openai",
  },
  {
    modelName: "gpt-4.1-mini",
    modelId: "gpt-4.1-mini",
    shortName: "gpt-4.1-mini",
    modelIcon: "/assets/icons/model-icons/chatgpt.svg",
    provider: "openai",
  },
  {
    modelName: "Deepseek R1",
    modelId: "deepseek/deepseek-r1",
    shortName: "Deepseek R1",
    modelIcon: "/assets/icons/model-icons/deepseek.svg",
    provider: "openrouter",
  },
  {
    modelName: "Deepseek V3",
    modelId: "deepseek/deepseek-chat-v3-0324",
    shortName: "Deepseek V3",
    modelIcon: "/assets/icons/model-icons/deepseek.svg",
    provider: "openrouter",
  },
  {
    modelName: "Gemini 2.0",
    modelId: "google/gemini-2.0-flash-001",
    shortName: "Gemini 2.0",
    modelIcon: "/assets/icons/model-icons/gemini.svg",
    provider: "openrouter",
  },
  {
    modelName: "llama 3.3",
    modelId: "llama-3.3-70b-versatile",
    shortName: "llama3.3",
    modelIcon: "/assets/icons/model-icons/meta.svg",
    provider: "groq",
  },
  {
    modelName: "llama 4 maverick",
    modelId: "meta-llama/llama-4-maverick-17b-128e-instruct",
    shortName: "llama 4 maverick",
    modelIcon: "/assets/icons/model-icons/meta.svg",
    provider: "groq",
  },
];

export const LanguagesList = [
  { code: "ar", name: "Arabic" },
  { code: "as", name: "Assamese" },
  { code: "bn", name: "Bengali" },
  { code: "ceb", name: "Cebuano" },
  { code: "zh", name: "Chinese" },
  { code: "cs", name: "Czech" },
  { code: "da", name: "Danish" },
  { code: "nl", name: "Dutch" },
  { code: "en", name: "English" },
  { code: "fi", name: "Finnish" },
  { code: "fr", name: "French" },
  { code: "de", name: "German" },
  { code: "el", name: "Greek" },
  { code: "gu", name: "Gujarati" },
  { code: "he", name: "Hebrew" },
  { code: "hi", name: "Hindi" },
  { code: "hu", name: "Hungarian" },
  { code: "id", name: "Indonesian" },
  { code: "it", name: "Italian" },
  { code: "ja", name: "Japanese" },
  { code: "kn", name: "Kannada" },
  { code: "ko", name: "Korean" },
  { code: "ms", name: "Malay" },
  { code: "ml", name: "Malayalam" },
  { code: "mr", name: "Marathi" },
  { code: "ne", name: "Nepali" },
  { code: "no", name: "Norwegian" },
  { code: "or", name: "Odia" },
  { code: "fa", name: "Persian" },
  { code: "pl", name: "Polish" },
  { code: "pt", name: "Portuguese" },
  { code: "pa", name: "Punjabi" },
  { code: "ro", name: "Romanian" },
  { code: "ru", name: "Russian" },
  { code: "sa", name: "Sanskrit" },
  { code: "es", name: "Spanish" },
  { code: "sv", name: "Swedish" },
  { code: "tl", name: "Tagalog" },
  { code: "ta", name: "Tamil" },
  { code: "te", name: "Telugu" },
  { code: "th", name: "Thai" },
  { code: "tr", name: "Turkish" },
  { code: "uk", name: "Ukrainian" },
  { code: "ur", name: "Urdu" },
  { code: "vi", name: "Vietnamese" },
];

export const GLOBAL_AGENT_META_DATA = {
  agentName: "Global Chat",
  agnoId: "Global_chat",
  description:
    "Try Kroolo's global chat to ask any specific question or search for anything.",
  agentAvatar: "/assets/icons/ChatWithProjectAI.svg",
  referenceName: "Global Chat",
};
