import {
  ArrowDown,
  Check,
  ChevronDown,
  ChevronUp,
  Download,
  Edit,
  FileText,
  HammerIcon,
  Image,
  Plus as PlusIcon,
  RefreshCw,
  Save,
  SendIcon,
  Trash,
  Video,
  Volume2,
  X,
} from "lucide-react";

import type { IconTypeMap } from "./types";
import {
  AgentIcon,
  AgnoIcon,
  AgnoTag,
  AIToolIcon,
  AnthropicIcon,
  AnthropicLogo,
  AudioIcon,
  AwsLogo,
  AzureLogo,
  BrainIcon,
  CohereLogo,
  DeepseekIcon,
  DeepseekLogo,
  DocIcon,
  DocxIcon,
  ExcelIcon,
  ExportIcon,
  FireworksLogo,
  GeminiIcon,
  GeminiLogo,
  GptIcon,
  GroqLogo,
  ImageIcon,
  KrooloIcon,
  LoaderIcon,
  MarkdownIcon,
  MetaIcon,
  MistralLogo,
  NextjsTag,
  OllamaLogo,
  OpenAILogo,
  PDFIcon,
  PdfIcon,
  PptIcon,
  ReasoningIcon,
  SearchIcon,
  ShadcnTag,
  SheetIcon,
  TailwindTag,
  TaskIcon,
  ToolSourcesLoaderIcon,
  TxtIcon,
  UnknownFormatIcon,
  UserIcon,
  VideoIcon,
  XaiLogo,
} from "./custom-icons";

export const ICONS: IconTypeMap = {
  "open-ai": OpenAILogo,
  mistral: MistralLogo,
  "loading-icon": LoaderIcon,
  "tool-loader":ToolSourcesLoaderIcon,
  gemini: GeminiLogo,
  aws: AwsLogo,
  export: ExportIcon,
  "export-pdf": PDFIcon,
  "export-mark": MarkdownIcon,
  "export-docx": DocxIcon,
  azure: AzureLogo,
  anthropic: AnthropicLogo,
  groq: GroqLogo,
  fireworks: FireworksLogo,
  deepseek: DeepseekLogo,
  cohere: CohereLogo,
  ollama: OllamaLogo,
  xai: XaiLogo,
  brain: BrainIcon,
  agno: AgnoIcon,
  user: UserIcon,
  agent: AgentIcon,
  sheet: SheetIcon,
  tool: AIToolIcon,
  nextjs: NextjsTag,
  shadcn: ShadcnTag,
  tailwind: TailwindTag,
  search: SearchIcon,
  reasoning: ReasoningIcon,
  "agno-tag": AgnoTag,
  refresh: RefreshCw,
  edit: Edit,
  save: Save,
  kroolo: KrooloIcon,
  references: FileText,
  image: Image,
  video: Video,
  audio: Volume2,
  x: X,
  "arrow-down": ArrowDown,
  send: SendIcon,
  download: Download,
  hammer: HammerIcon,
  check: Check,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  "plus-icon": PlusIcon,
  trash: Trash,
  anthropic_icon: AnthropicIcon,
  gpt_icon: GptIcon,
  deepseek_icon: DeepseekIcon,
  meta_icon: MetaIcon,
  gemini_icon: GeminiIcon,
  ppt_icon: PptIcon,
  pdf_icon: PdfIcon,
  txt_icon: TxtIcon,
  video_icon: VideoIcon,
  audio_icon: AudioIcon,
  image_icon: ImageIcon,
  docx_icon: DocIcon,
  csv_icon: ExcelIcon,
  unknown_icon: UnknownFormatIcon,
  tasks: TaskIcon,
};
