apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: blue-fe-es-search-qastage01
  namespace: fe-es-search-qastage01
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: blue-fe-es-search-qastage01
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 85 # Scale if CPU utilization > 75%
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80 # Scale if memory utilization > 70%
